
setwd('/Users/zhuofanmou/Documents/PhD Exeter/ClariomD/alternative_splicing/R_workspace_v2/limmaVoom_DGEA_TCGA')
getwd()
library(org.Hs.eg.db)
hs <- org.Hs.eg.db
my.symbols <- c("SRSF7",
                "CELF1",
                "DAZAP1",
                "ESRP1",
                "ESRP2",
                "CELF2",
                "FMR1",
                "RBFOX1",
                "RBFOX2",
                "HNRNPA0",
                "HNRNPA1",
                "HNRNPA2B1",
                "HNRNPA3",
                "HNRNPC",
                # "HNRNPC1",
                # "HNRNPC2",
                "HNRNPD",
                # "HNRNPD0",
                "HNRNPDL",
                # "HNRNPE1",
                # "HNRNPE2",
                "HNRNPF",
                "RBMX",
                "HNRNPH1",
                "HNRNPH2",
                "HNRNPH3",
                "PTBP1",
                # "HNRNPJ",
                "HNRNPK",
                "HNRNPL",
                "HNRNPLL",
                "HNRNPM",
                # "HNRNPP(TLS)",
                "SYNCRIP",
                "HNRNPU",
                # "HTRA2ALPHA",
                # "HTRA2BETA1",
                "ELAVL2",
                "ELAVL3",
                "ELAVL4",
                "ELAVL1",
                "KHSRP",
                "MBNL1",
                "NOVA1",
                "NOVA2",
                "PTBP2",
                "SFPQ",
                "QKI",
                "RBM25",
                "RBM4",
                "RBM5",
                "KHDRBS1",
                "SF3B1",
                "SRSF2",
                "SF1",
                "SRSF1",
                "KHDRBS2",
                "KHDRBS3",
                "SRRM1",
                "SRSF3",
                "SRSF9",
                "SRSF10",
                "SRSF5",
                "SRP54",
                "SRSF6",
                "SRSF4",
                "TARDBP",
                "TIAL1",
                "TIA1",
                "YBX1",
                "ZRANB2")

Entrez <- AnnotationDbi::select(hs, 
       keys = my.symbols,
       columns = c("ENTREZID", "SYMBOL","ENSEMBL"),
       keytype = "SYMBOL")
View(Entrez)
write.xlsx(Entrez,"SF_Entrez_EnsID.xlsx")
